development:
  dialect: "mysql"
  database: "go_app_start_development"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "d3vus3r"
  encoding: "utf8mb4_general_ci"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:d3vus3r@(localhost:3306)/go_app_start_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:d3vus3r@(localhost:3306)/go_app_start_production?parseTime=true&multiStatements=true&readTimeout=1s"}}
